version: '3.8'
services:
  backend:
    build: 
      context: /Dockerfiles
      dockerfile: php.Dockerfile
    container_name: backend_svc
    ports:
      - 8080:80
    volumes:
      - ./code/:/var/www/html
    depends_on:
      - database
    networks:
      app_network:
        aliases:
          - backend_host

  database:
    build: 
      context: /Dockerfiles
      dockerfile: mariadb.Dockerfile
    container_name: mariadb_svc
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=custom_db
      - MYSQL_ROOT_PASSWORD=Custom.2022
    volumes:
      - ./schemas/:/var/lib/mysql
    networks:
      app_network:
        aliases:
          - mariadb_host

volumes:
  code: {}
  schemas: {}

networks:
  app_network:
    name: app_net
    driver: bridge
    ipam:
      driver: default
